export const LOAD_TREASURY_DATA = '@@TREASURY/LOAD_DATA';
export const LOAD_TREASURY_DATA_SUCCESS = '@@TREASURY/LOAD_DATA_SUCCESS';
export const LOAD_TREASURY_DATA_FAILURE = '@@TREASURY/LOAD_DATA_FAILURE';
