name: Build and Package .dapp

on:
  push:
    branches:
      - mainnet
      - workflow-test
  pull_request:
    branches:
      - mainnet
      - workflow-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Use the version of Node.js required by your project

    - name: Install dependencies
      run: yarn install

    - name: Build the project
      run: yarn build

    - name: Create folder structure
      run: mkdir -p dao-voting/app

    - name: Copy build files
      run: cp -r html/* dao-voting/app/

    - name: Create manifest.json
      run: |
        echo '{
          "name":  "BeamX DAO Voting",
          "description":  "Voting on Beam community proposals",
          "icon":  "localapp/app/logo.svg",
          "url":  "localapp/app/index.html",
          "version":  "1.0.0",
          "api_version":  "7.0",
          "min_api_version":  "7.0",
          "guid":  "c26538f5ce9e410b89c1fd0dff783f97"
        }' > dao-voting/manifest.json

    - name: Package into .dapp file
      run: |
        cd dao-voting
        zip -r ../dao-voting.dapp ./*
        cd ..

    - name: Upload .dapp file
      uses: actions/upload-artifact@v4
      with:
        name: dao-voting.dapp
        path: dao-voting.dapp
